language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
    - php: nightly
      env:
        - COMPOSER_ARGS="--no-suggest --ignore-platform-reqs"
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - composer --version
  - travis_retry composer install --no-interaction --prefer-source $COMPOSER_ARGS

script:
  - mkdir -p ./build/logs
  - php vendor/bin/phpunit --coverage-clover=./build/logs/coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar -O ocular.phar
  - travis_retry php ocular.phar self-update
  - php ocular.phar --version
  - travis_retry php ocular.phar code-coverage:upload --repository=b/gentlero/bitbucket-api --format=php-clover ./build/logs/coverage.clover

notifications:
  webhooks:
    urls:
      secure: "Xqj40L7H7t01GvXZWLFGBHJSelhNZeGO107+EyBr3BjGX6iurDUWE1JAAWfEA5+TXE1Nv902t5EaXzc4KnRSwXwNjpVXj3cIOZX/xlQ4bE0rtU5Fzd93aULtshIAfexN99AG6iV4URtIlWYBgwqV7vadMy/UEgBlELLKUQS0GOI="
